name: Publish VSCode Extension

on:
  create:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14-buster
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Go to correct folder
        run: cd symfony-vscode-fixed
        
      - name: Install dependencies
        run: yarn install

      - name: Compile
        run: yarn run vscode:prepublish

      - name: Install VSCE
        run: yarn global add vsce

      - name: Package Extention
        run: vsce package
        
      - name: Publish
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
