name: Publish VSCode Extension

on:
  create:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./symfony-vscode-fixed
    container:
      image: node:14-buster
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List folder
        run: ls -la
        
      - name: Install dependencies
        run: yarn install && yarn global add vsce

      - name: Package Extention
        run: vsce package
        
      - name: Publish
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
